[package]
name = "codehq-ts-api"
version = "0.1.0"
edition = "2018"

[dependencies]
actix-web = "*"
log = "*"
env_logger = "*"
alcoholic_jwt = "*"
lazy_static = "*"
actix-web-httpauth = "*"
openidconnect = "*"
dotenv = "*"
reqwest = { version = "*", features = ["json"] }
serde_json = "*"
